#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : open-iscsi
Version  : 2.0.875
Release  : 22
URL      : https://github.com/open-iscsi/open-iscsi/archive/2.0.875.tar.gz
Source0  : https://github.com/open-iscsi/open-iscsi/archive/2.0.875.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: open-iscsi-bin
Requires: open-iscsi-config
Requires: open-iscsi-doc
BuildRequires : open-isns-dev
BuildRequires : openssl-dev
BuildRequires : util-linux-dev
Patch1: systemd-units-with-name-generation.patch

%description
=================================================================
Linux* Open-iSCSI

%package bin
Summary: bin components for the open-iscsi package.
Group: Binaries
Requires: open-iscsi-config

%description bin
bin components for the open-iscsi package.


%package config
Summary: config components for the open-iscsi package.
Group: Default

%description config
config components for the open-iscsi package.


%package doc
Summary: doc components for the open-iscsi package.
Group: Documentation

%description doc
doc components for the open-iscsi package.


%prep
%setup -q -n open-iscsi-2.0.875
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1512433480
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1512433480
rm -rf %{buildroot}
%make_install
## make_install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system
cp etc/systemd/* %{buildroot}/usr/lib/systemd/system
cp utils/iscsi-gen-initiatorname %{buildroot}/usr/bin
chmod +x %{buildroot}/usr/bin/iscsi-gen-initiatorname
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iscsi-gen-initiatorname
/usr/bin/iscsi-iname
/usr/bin/iscsi_discovery
/usr/bin/iscsiadm
/usr/bin/iscsid
/usr/bin/iscsiuio

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/iscsi-gen-initiatorname.service
/usr/lib/systemd/system/iscsid.service
/usr/lib/systemd/system/iscsid.socket

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
