#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : open-iscsi
Version  : 2.0.877
Release  : 29
URL      : https://github.com/open-iscsi/open-iscsi/archive/2.0.877.tar.gz
Source0  : https://github.com/open-iscsi/open-iscsi/archive/2.0.877.tar.gz
Summary  : iSCSI userspace library
Group    : Development/Tools
License  : GPL-2.0
Requires: open-iscsi-bin = %{version}-%{release}
Requires: open-iscsi-config = %{version}-%{release}
Requires: open-iscsi-lib = %{version}-%{release}
Requires: open-iscsi-license = %{version}-%{release}
Requires: open-iscsi-man = %{version}-%{release}
BuildRequires : kmod-dev
BuildRequires : open-isns-dev
BuildRequires : openssl-dev
BuildRequires : systemd-dev
BuildRequires : util-linux-dev
Patch1: 0001-add-interfacename-generator.patch
Patch2: 0002-Install-iscsistart.patch
Patch3: 0003-Remove-Werror-from-CFLAGS.patch
Patch4: 0004-Fix-link-with-libkmod-and-libsystemd.patch

%description
=================================================================
Linux* Open-iSCSI

%package autostart
Summary: autostart components for the open-iscsi package.
Group: Default

%description autostart
autostart components for the open-iscsi package.


%package bin
Summary: bin components for the open-iscsi package.
Group: Binaries
Requires: open-iscsi-config = %{version}-%{release}
Requires: open-iscsi-license = %{version}-%{release}
Requires: open-iscsi-man = %{version}-%{release}

%description bin
bin components for the open-iscsi package.


%package config
Summary: config components for the open-iscsi package.
Group: Default

%description config
config components for the open-iscsi package.


%package dev
Summary: dev components for the open-iscsi package.
Group: Development
Requires: open-iscsi-lib = %{version}-%{release}
Requires: open-iscsi-bin = %{version}-%{release}
Provides: open-iscsi-devel = %{version}-%{release}

%description dev
dev components for the open-iscsi package.


%package lib
Summary: lib components for the open-iscsi package.
Group: Libraries
Requires: open-iscsi-license = %{version}-%{release}

%description lib
lib components for the open-iscsi package.


%package license
Summary: license components for the open-iscsi package.
Group: Default

%description license
license components for the open-iscsi package.


%package man
Summary: man components for the open-iscsi package.
Group: Default

%description man
man components for the open-iscsi package.


%prep
%setup -q -n open-iscsi-2.0.877
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539906746
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1539906746
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/open-iscsi
cp COPYING %{buildroot}/usr/share/package-licenses/open-iscsi/COPYING
%make_install
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
cp etc/systemd/* %{buildroot}/usr/lib/systemd/system
ln -s ../iscsid.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/
cp utils/iscsi-gen-initiatorname %{buildroot}/usr/bin
chmod +x %{buildroot}/usr/bin/iscsi-gen-initiatorname
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/iscsid.service

%files bin
%defattr(-,root,root,-)
/usr/bin/iscsi-gen-initiatorname
/usr/bin/iscsi-iname
/usr/bin/iscsi_discovery
/usr/bin/iscsi_fw_login
/usr/bin/iscsi_offload
/usr/bin/iscsiadm
/usr/bin/iscsid
/usr/bin/iscsistart
/usr/bin/iscsiuio

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/iscsid.service
/usr/lib/systemd/system/iscsi-gen-initiatorname.service
/usr/lib/systemd/system/iscsi.service
/usr/lib/systemd/system/iscsid.service
/usr/lib/systemd/system/iscsid.socket

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libopeniscsiusr.so
/usr/lib64/pkgconfig/libopeniscsiusr.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopeniscsiusr.so.0
/usr/lib64/libopeniscsiusr.so.0.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/open-iscsi/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/iscsi-iname.8
/usr/share/man/man8/iscsi_discovery.8
/usr/share/man/man8/iscsi_fw_login.8
/usr/share/man/man8/iscsiadm.8
/usr/share/man/man8/iscsid.8
/usr/share/man/man8/iscsistart.8
/usr/share/man/man8/iscsiuio.8
